### ISSUE TITLE
How to choose older version of youtube

### ISSUE THREAD

**Issue by gosndka** [kakathic/YT-AT#29]
As, the title says, I can't run newer versions of revanced on my android, since the app only supports android 8+ but my phone is android 7. Can anyone help me out?

**Comment by kakathic** [comment]
> As, the title says, I can't run newer versions of revanced on my android, since the app only supports android 8+ but my phone is android 7. Can anyone help me out?

Please select the latest version of android 7

**Comment by gosndka** [comment]
> > As, the title says, I can't run newer versions of revanced on my android, since the app only supports android 8+ but my phone is android 7. Can anyone help me out?
> 
> Please select the latest version of android 7

You can't, since youtube stopped supporting android 7 from 17.35 version, also I meant to ask how to choose specific version of youtube in github actions? as I have forked your repo

**Comment by kakathic** [comment]
> > > As, the title says, I can't run newer versions of revanced on my android, since the app only supports android 8+ but my phone is android 7. Can anyone help me out?
> > 
> > 
> > Please select the latest version of android 7
> 
> You can't, since youtube stopped supporting android 7 from 17.35 version, also I meant to ask how to choose specific version of youtube in github actions? as I have forked your repo

![Screenshot_2022-10-26-23-05-07-083_com android chrome](https://user-images.githubusercontent.com/28665018/198077615-e1a31ab0-ae1e-4e4e-a3aa-249c26630c64.jpg)

**Comment by kakathic** [comment]
Please enter the version number

**Comment by gosndka** [comment]
> Please enter the version number
Getting this error
[logs_11.zip](https://github.com/kakathic/YT-AT/files/9876630/logs_11.zip)

**Comment by kakathic** [comment]
https://github.com/kakathic/YT-AT/releases/tag/V17-33-42

Looks like the revanced cli tool doesn't support building old versions

**Comment by gosndka** [comment]
> https://github.com/kakathic/YT-AT/releases/tag/V17-33-42
> 
> Looks like the revanced cli tool doesn't support building old versions

That's a shame and am already using that version and I keep getting ads on my feeds its annonying tbh

**Comment by kakathic** [comment]
use vanced

**Comment by gosndka** [comment]
Even that is getting ads nowadays, thanks for your help though

> use vanced
