### ISSUE TITLE
App not installed on MIUI 12.5.6

### ISSUE THREAD

**Issue by Aurobindoji** [kakathic/YT-AT#30]
App not installed on MIUI 12.5.6 Redmi 8a dual
India

**Comment by kakathic** [comment]
send log magisk

**Comment by katiehedrick** [comment]
@Aurobindoji I had the same issue, I'm not sure if Redmi phones have the Google Play Store but you must toggle off "Scan apps with Play Protect" before installing any patched apps. I would also recommend toggling off "Improve harmful app detection".
![Screenshot_20221105-154639](https://user-images.githubusercontent.com/91288575/200138343-895252ad-1567-422d-8b8f-febd07dc45cd.png)
