### ISSUE TITLE
"Remember playback rate changes" not work

### ISSUE THREAD

**Issue by games1tw** [kakathic/YT-AT#32]
Remember playback rate changes
Playback rate changes only apply to the
current video

not work

**Comment by kakathic** [comment]
> Remember playback rate changes Playback rate changes only apply to the current video
> 
> not work

Try the latest version.

**Comment by games1tw** [comment]
It is working fine now, thank you. 

> > Remember playback rate changes Playback rate changes only apply to the current video
> > not work
> 
> Try the latest version.

It is working fine now, thank you.
