### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Hamood111** [kakathic/YT-AT#37]
18.5.40 is the last update working on magisk after that to this update before 9 hours not working the update before this asking for microg and even after installed still not working but this update 😅 is not working at all no asking for microg nothing just another hopeless update idn why u keep updating if module not working anymore

**Comment by kakathic** [comment]
> 18.5.40 is the last update working on magisk after that to this update before 9 hours not working the update before this asking for microg and even after installed still not working but this update 😅 is not working at all no asking for microg nothing just another hopeless update idn why u keep updating if module not working anymore

Updating ...
