### ISSUE TITLE
great work 

### ISSUE THREAD

**Issue by Hamood111** [kakathic/YT-AT#39]
good job on this update working fine with magisk no issues at all until now but u removed the auto brightness when rotating the screen u need to put brightness level by your self there's no more Auto but at the same time u add 3 second double tap which a great new feature I know it's build on YouTube revanced because now I can see the black logo when I open the app but the best thing in your module it's still bring shorts clips and that's something I miss it in the revanced module anyway good job I like it ❤️ thanks kakathic

**Comment by kakathic** [comment]
Yt-re and yt-ext are different you can try either.
