### ISSUE TITLE
virus alert 

### ISSUE THREAD

**Issue by senolfndk** [kakathic/YT-AT#40]
![Screenshot_20230512-145231_Google Play Store.jpg](https://github.com/kakathic/YT-AT/assets/52818836/75981af2-b1ce-423b-90f9-dbf257f46d43)

**Comment by kakathic** [comment]
Due to signature issues will be revised again.

**Comment by kakathic** [comment]
Fixed you can download the latest apk again.

**Comment by senolfndk** [comment]
> Düzeltildi, en son apk'yı tekrar indirebilirsiniz.

ok

**Comment by senolfndk** [comment]
same problem 😒
