### ISSUE TITLE
Virustotal PUA

### ISSUE THREAD

**Issue by anxiouslelimo** [kakathic/YT-AT#44]
<img width="845" alt="image" src="https://github.com/kakathic/YT-AT/assets/115996455/bfb83a39-b8f0-4a5b-b1cd-fa73af346dec">

**Comment by kakathic** [comment]
https://github.com/kakathic/YT-AT/blob/Vip/.github/Tools/testkey.x509.pem

https://github.com/kakathic/YT-AT/blob/Vip/.github/Tools/testkey.pk8

https://github.com/kakathic/YT-AT/blob/Vip/.github/Tools

You can check the signature here.

**Comment by kakathic** [comment]
Use Google's signature

**Comment by anxiouslelimo** [comment]
> Use Google's signature

How to do that?
