### ISSUE TITLE
Buffering problem 

### ISSUE THREAD

**Issue by MallinathR** [kakathic/YT-AT#45]
I was  downloaded YT provided by you on GitHub. But the problem was arising that while watching any video, after a 1 min duration it will start buffering, even my internet was too good, so now what to do????

**Comment by kakathic** [comment]
Try other people's mods and if it still doesn't work, I don't know where the problem is

**Comment by Rishiop50** [comment]
Same problem was happened with me.

**Comment by kakathic** [comment]
This problem I don't know how to fix you can ask the creators of the tool patch

**Comment by Sudeepxl20** [comment]
There is no fix for this is a problem with Google blocking video playback by giving 403 response codes it via MICROG there is many ways to fix this problem


1, root your device (works 100%)
2 uninstall all revanced related apps including microg then install latest version

3,try turning off and on (SPOOF PLAYER PARAMETERS) Flag in ReVanced Settings

4, use it in incognito mode it works

**Comment by Sudeepxl20** [comment]
> There is no fix for this is a problem with Google blocking video playback by giving 403 response codes it via MICROG there is many ways to fix this problem
> 
> 1, root your device (works 100%) 2 uninstall all revanced related apps including microg then install latest version
> 
> 3,try turning off and on (SPOOF PLAYER PARAMETERS) Flag in ReVanced Settings
> 
> 4, use it in incognito mode it works

Add this info in the bottom off the repo see users can love there problem (just a suggestion) Thank you
