### ISSUE TITLE
Suggestion rex Extended logo

### ISSUE THREAD

**Issue by Sudeepxl20** [kakathic/YT-AT#48]
Ple consider using rex coustom logo build 
![IMG_20230816_000824_942](https://github.com/kakathic/YT-AT/assets/111219466/4c90e656-6630-477f-8a3e-99c801013f8d)

Official rex Extended logo or Coustom ICON revacify red

**Comment by kakathic** [comment]
https://github.com/kakathic/YT-AT/blob/Vip/.github/options/Ytx.md

You can change this file and run it as a tutorial to build your own YouTube

**Comment by kakathic** [comment]
I will only use the official YouTube logo, sorry for not being able to accommodate your request.
