### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by Hamood111** [kakathic/YT-AT#49]
thank u kakathic for this beautiful work I just found one issue the module and app working fine but there's magisk detection in momo after I uninstalled the module the detection disappeared I hope u fix this issue in next update by the way this issue is not exist on other YouTube modules peace

**Comment by kakathic** [comment]
I don't quite understand what you are talking about.

**Comment by Hamood111** [comment]
2 pic before and after using the module
![IMG_20230825_023637](https://github.com/kakathic/YT-AT/assets/116981650/5a6ef58b-e1b7-4f6f-a917-a0b5e350a850)
![IMG_20230825_023606](https://github.com/kakathic/YT-AT/assets/116981650/c537a1fb-702d-49f7-8c34-895c61b9be9f)

**Comment by Hamood111** [comment]
i will close it because there's no issues with using but there's detecting maybe this detecting will make some issues for other apps but for me everything is fine with your module i just want u to know about this issue thanks
